hk_camera_capture:
  ros__parameters:
    # 连接优先级：camera_ip > camera_sn > camera_index
    camera_ip: ""            # 例: "192.168.1.100"
    camera_sn: ""            # 例: "K12345678"
    camera_index: 0

    topic_name: "/image_raw"
    frame_id: "hk_camera"

    use_software_trigger: false
    acq_framerate_enable: true

    exposure_time: 8000.0    # us
    gain: 1.0                # 相机增益（单位取决于机型）
    frame_rate: 60.0         # Hz
    pixel_format: "BGR8"     # 发布编码：BGR8 或 MONO8

    reconnect_interval_sec: 2.0
    qos_reliable: true
