hik_usb_bgr8_pub:
  ros__parameters:
    # 连接方式（二选一：SN 或 IP；SN 务必加引号避免被当作数字）
    serial_number: "00E89503815"
    ip_address: ""

    # 发布与重连
    frame_id: "camera_frame"
    image_topic: "image_raw"
    qos_reliable: false        # false=Best Effort（推荐），true=Reliable
    reconnect_interval_ms: 2000

    # 相机参数
    exposure_auto: 2           # 0=Off,1=Once,2=Continuous
    exposure_time: 5000.0
    gain_auto: 2
    gain: 6.0
    acquisition_fps: 180.0
    pixel_format: "BGR8"
